"use client";
import { useEffect, useRef, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
type Lead = { name: string; email: string; cpf: string; phone: string };
type Charge = { transactionId: string; qrCode: string; amount: number; expiresAt?: string | null };

export default function V6Page() {
  const [charge, setCharge] = useState<Charge | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState(false); const [approved, setApproved] = useState(false); const createPromise = useRef<Promise<Charge> | null>(null);
  useEffect(() => { document.body.style.overflowX = "hidden"; return () => { document.body.style.overflowX = ""; }; }, []);
  useEffect(() => { let cancelled = false; const lead = JSON.parse(sessionStorage.getItem("gas-lead") || "null") as Lead | null; const offerId = sessionStorage.getItem("gas-offer"); const savedOffer = sessionStorage.getItem("gas-charge-offer"); const savedCharge = sessionStorage.getItem("gas-charge"); if (savedCharge && savedOffer === offerId) { setCharge(JSON.parse(savedCharge)); setLoading(false); return () => { cancelled = true; }; } if (!lead || !offerId) { setError("Não encontramos os dados da consulta. Volte e preencha o formulário novamente."); setLoading(false); return () => { cancelled = true; }; } if (!createPromise.current) { createPromise.current = fetch("/api/pix/create", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...lead, offerId }) }).then(async (r) => { const data = await r.json(); if (!r.ok) throw new Error(data.error || "Não foi possível gerar o Pix."); return data as Charge; }); } createPromise.current.then((data) => { if (!cancelled) { setCharge(data); setLoading(false); sessionStorage.setItem("gas-charge", JSON.stringify(data)); sessionStorage.setItem("gas-charge-offer", offerId); } }).catch((e) => { if (!cancelled) { setError(e.message); setLoading(false); } }); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!charge || approved) return; const check = async () => { const r = await fetch("/api/pix/status", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transactionId: charge.transactionId }) }); const data = await r.json(); if (data.status === "approved") setApproved(true); }; const timer = window.setInterval(check, 5000); check(); return () => window.clearInterval(timer); }, [charge, approved]);
  async function copyPix() { if (!charge) return; try { await navigator.clipboard.writeText(charge.qrCode); setCopied(true); window.setTimeout(() => setCopied(false), 2500); } catch { setError("Não foi possível copiar automaticamente. Selecione e copie o código manualmente."); } }
  if (approved) return <main className="form-shell"><div className="form-heading"><h1>Pagamento aprovado!</h1><p>Seu pagamento Pix foi confirmado com sucesso.</p></div></main>;
  return <main className="form-shell" style={{ overflowX: "hidden" }}><div className="form-heading"><p className="form-kicker">PAGAMENTO PIX</p><h1>Finalize sua solicitação</h1><p>Escaneie o QR Code ou copie o código Pix abaixo.</p></div>{loading && <div role="status" aria-live="polite" style={{ display: "grid", justifyItems: "center", gap: 12, margin: "34px auto", color: "#5c6678", fontSize: 14 }}><span style={{ width: 32, height: 32, border: "4px solid #dbe5f5", borderTopColor: "#1351b4", borderRadius: "50%", animation: "pix-spin .8s linear infinite" }} /><span>Gerando seu Pix, aguarde um momento…</span><style>{"@keyframes pix-spin { to { transform: rotate(360deg); } }"}</style></div>}{error && <p role="alert" style={{ color: "#b42318", textAlign: "center" }}>{error}</p>}{charge && <div style={{ display: "grid", justifyItems: "center", gap: 14, marginTop: 24, padding: "22px 18px", background: "#fff", border: "1px solid #e1e6ee", borderRadius: 16, boxShadow: "0 10px 28px #193b7510", overflow: "hidden" }}><strong style={{ color: "#1351b4", fontSize: 20 }}>R$ {(charge.amount / 100).toFixed(2).replace(".", ",")}</strong><div style={{ display: "grid", placeItems: "center", padding: 12, border: "1px solid #dce3ee", borderRadius: 12, background: "#fff" }}><QRCodeSVG value={charge.qrCode} size={180} level="M" title="QR Code PIX" /></div><textarea readOnly value={charge.qrCode} aria-label="Código Pix copia e cola" style={{ width: "100%", minHeight: 88, maxHeight: 120, padding: "11px 12px", border: "1px solid #cbd5e1", borderRadius: 9, outline: "none", resize: "none", overflowY: "auto", overflowX: "hidden", overflowWrap: "anywhere", wordBreak: "break-word", color: "#435066", background: "#f8fafc", fontSize: 12, lineHeight: 1.45 }} /><button type="button" className="official-button" onClick={copyPix}>{copied ? "Código copiado ✓" : "Copiar código Pix"}</button><small style={{ color: "#5c6678", fontSize: 12 }}>Aguardando confirmação do pagamento…</small></div>}</main>;
}
